version: "3.3"
services:
  report:
    image: pdf-report-demo
    build: .
    depends_on:
      - redis
    ports:
      - 8080:8080
    restart: unless-stopped
  redis:
    image: redis
    volumes:
      - ./dump.rdb:/data/dump.rdb
    ports:
      - 6379:6379
    restart: unless-stopped
